site_name: Aprendendo Elixir
site_author: Você, desenvolvedor!

theme: 
    name: material
    language: pt

nav:
    - index.md
    - 01_elixir-1-tipos.md
    - 02_elixir-2-operacoes.md
    - 03_elixir-3-colecoe.md
    - 04_elixir-4-colecoe.md
    - 05_elixir-5-coleco.md
    - 06_elixir-6-usando-funcoes-em-enu.md
    - 07_elixir-7-variaveis-e-pattern-.md
    - 08_elixir-8-estruturas-de-controle-com-if-unless-case-con.md
    - 09_elixir-9.md
    - 10_elixir-10-opera.md
    - 11_elixir-11.md
    - 12_elixir-12-usan.md
    - 13_elixir-13-conhecend.md
    - 14_elixir-14-documentando-se.md
    - 15_elixir-15-compre.md
    - 16_elixir-16.md
    - 17_elixir-17-dat.md
    - 18_elixir-18-iex.md
    - 19_elixir-19-tarefas-customizada.md
    - 20_elixir-20-interoperabilidade-co.md
    - 21_elixir-21-tratamento-.md
    - 22_elixir-22-criando-um-ex.md
    - 23_elixir-22-criando-um-script-que-busca-do-google-e-salva-em.md
    - 24_elixir-23-conc.md
    - 25_elixir-24-otp-g.md
    - 26_elixir-25-otp-su.md
    - 27_elixir-26-otp-dynamicsu.md
    - 28_elixir-27-otp-distribuicao-conceitos.md
    - 29_elixir-28-otp-distribuicao-consolidando-c.md
    - 30_elixir-29-exemplo-pratico-criando-uma-aplicacao-distribuida-rodando-e.md
    - 31_elixir-30-appl.md
    - 32_elixir-31-metapro.md
    - 33_elixir-32-usando-macros-exemplo.md
    - 34_elixir-33-especificacoes.md
    - 35_elixir-34-be.md
    - 36_elixir-35-protocolos-e-poli.md
    - 37_elixir-3.md
